version: "3"
services:
  pythonapp:
    build: 
      context: ./app
      network: host
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mysql

  mysql:
    build: ./db
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data: {}
